version: "3.8"

services:
  web:
    build: .
    container_name: simple_lms
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - lms-network

  database:
    image: postgres:15-alpine
    container_name: lms_database
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lms_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      lms-network:
        aliases:
          - db
          - postgres
          - database

volumes:
  postgres_data:

networks:
  lms-network:
    driver: bridge
